# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mat_pre <- function(dat) {
    .Call(`_dexterMML_mat_pre`, dat)
}

prox_dich <- function(isum, psum, inp, pni, icnp, pcni, ip, pi, max_iter = 20L, min_change = 0.01) {
    .Call(`_dexterMML_prox_dich`, isum, psum, inp, pni, icnp, pcni, ip, pi, max_iter, min_change)
}

