# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

theta_2pl <- function(a, A, b, ncat, pni, pcni, pi, px, WLE = FALSE, USE_A = TRUE) {
    .Call(`_dexterMML_theta_2pl`, a, A, b, ncat, pni, pcni, pi, px, WLE, USE_A)
}

se_theta_2pl <- function(a, A, b, ncat, pni, pcni, pi, theta, WLE = FALSE, USE_A = TRUE) {
    .Call(`_dexterMML_se_theta_2pl`, a, A, b, ncat, pni, pcni, pi, theta, WLE, USE_A)
}

E_score <- function(theta, A, a, b, items, ncat) {
    .Call(`_dexterMML_E_score`, theta, A, a, b, items, ncat)
}

mat_pre <- function(dat, max_score) {
    .Call(`_dexterMML_mat_pre`, dat, max_score)
}

categorize <- function(pni, pcni, pi, icat, imax, max_cat, px) {
    .Call(`_dexterMML_categorize`, pni, pcni, pi, icat, imax, max_cat, px)
}

plot_data <- function(pcni, pi, px, inp, theta, a, item) {
    .Call(`_dexterMML_plot_data`, pcni, pi, px, inp, theta, a, item)
}

design_matrices <- function(pni, pcni, pi, pg, nit, ng) {
    .Call(`_dexterMML_design_matrices`, pni, pcni, pi, pg, nit, ng)
}

check_connected_c <- function(item, group, item_fixed) {
    .Call(`_dexterMML_check_connected_c`, item, group, item_fixed)
}

estimate_nrm <- function(a, b_start, ncat, pni, pcni, pi, px, theta, mu_start, sigma_start, gn, pgroup, item_fixed, ref_group = 0L, max_iter = 200L, pgw = 80L) {
    .Call(`_dexterMML_estimate_nrm`, a, b_start, ncat, pni, pcni, pi, px, theta, mu_start, sigma_start, gn, pgroup, item_fixed, ref_group, max_iter, pgw)
}

test_ll_nrm <- function(a, theta, r, par) {
    .Call(`_dexterMML_test_ll_nrm`, a, theta, r, par)
}

test_gradient_nrm <- function(a, theta, r, par) {
    .Call(`_dexterMML_test_gradient_nrm`, a, theta, r, par)
}

test_hess_nrm <- function(a, theta, r, par) {
    .Call(`_dexterMML_test_hess_nrm`, a, theta, r, par)
}

Oakes_nrm <- function(a, b, ncat, r, pni, pcni, pi, px, theta, mu, sigma, gn, pgroup, dsg_ii, dsg_gi, item_fixed, ref_group = 0L, pgw = 80L) {
    .Call(`_dexterMML_Oakes_nrm`, a, b, ncat, r, pni, pcni, pi, px, theta, mu, sigma, gn, pgroup, dsg_ii, dsg_gi, item_fixed, ref_group, pgw)
}

loglikelihood_2pl <- function(a, A, b, ncat, pni, pcni, pi, px, theta, mu, sigma, pgroup) {
    .Call(`_dexterMML_loglikelihood_2pl`, a, A, b, ncat, pni, pcni, pi, px, theta, mu, sigma, pgroup)
}

estimate_pl2 <- function(a, A_start, b_start, ncat, pni, pcni, pi, px, theta, mu_start, sigma_start, gn, pgroup, item_fixed, ip, inp, icnp, ref_group = 0L, A_prior = 0L, A_mu = 0, A_sigma = 0.5, use_m2 = 150L, max_iter = 200L, pgw = 80L) {
    .Call(`_dexterMML_estimate_pl2`, a, A_start, b_start, ncat, pni, pcni, pi, px, theta, mu_start, sigma_start, gn, pgroup, item_fixed, ip, inp, icnp, ref_group, A_prior, A_mu, A_sigma, use_m2, max_iter, pgw)
}

test_ll_p2 <- function(a, theta, r, par, prior = 0L) {
    .Call(`_dexterMML_test_ll_p2`, a, theta, r, par, prior)
}

test_gradient_p2 <- function(a, theta, r, par, prior = 0L) {
    .Call(`_dexterMML_test_gradient_p2`, a, theta, r, par, prior)
}

test_hess_p2 <- function(a, theta, r, par, prior = 0L) {
    .Call(`_dexterMML_test_hess_p2`, a, theta, r, par, prior)
}

test_ll_v2 <- function(a, A, b, ncat, theta, ip, pi, pcni, px, pgroup, inp, icnp, mu, sigma, item, pars) {
    .Call(`_dexterMML_test_ll_v2`, a, A, b, ncat, theta, ip, pi, pcni, px, pgroup, inp, icnp, mu, sigma, item, pars)
}

test_gr_v2 <- function(a, A, b, ncat, theta, ip, pi, pcni, px, pgroup, inp, icnp, mu, sigma, item, pars) {
    .Call(`_dexterMML_test_gr_v2`, a, A, b, ncat, theta, ip, pi, pcni, px, pgroup, inp, icnp, mu, sigma, item, pars)
}

test_hess_v2 <- function(a, A, b, ncat, theta, ip, pi, pcni, px, pgroup, inp, icnp, mu, sigma, item, pars) {
    .Call(`_dexterMML_test_hess_v2`, a, A, b, ncat, theta, ip, pi, pcni, px, pgroup, inp, icnp, mu, sigma, item, pars)
}

Oakes_pl2 <- function(a, A, b, ncat, r, pni, pcni, pi, px, theta, mu, sigma, gn, pgroup, dsg_ii, dsg_gi, item_fixed, ip, inp, icnp, ref_group = 0L, A_prior = 0L, A_mu = 0, A_sigma = 0.5, pgw = 80L) {
    .Call(`_dexterMML_Oakes_pl2`, a, A, b, ncat, r, pni, pcni, pi, px, theta, mu, sigma, gn, pgroup, dsg_ii, dsg_gi, item_fixed, ip, inp, icnp, ref_group, A_prior, A_mu, A_sigma, pgw)
}

plausible_values_c <- function(A, a, b, ncat, pni, pcni, pi, px, pop, popn, npv, starting_values, n_prior_updates = 10L, thin = 10L, pgw = 80L) {
    .Call(`_dexterMML_plausible_values_c`, A, a, b, ncat, pni, pcni, pi, px, pop, popn, npv, starting_values, n_prior_updates, thin, pgw)
}

sim_2plc <- function(a, A, b, ncat, theta) {
    .Call(`_dexterMML_sim_2plc`, a, A, b, ncat, theta)
}

test_nlm <- function(a, theta, r, par_in) {
    invisible(.Call(`_dexterMML_test_nlm`, a, theta, r, par_in))
}

